#!/bin/bash
recipe=$1
# set -x 
bblayers=$( grep -Poz 'BBLAYERS.*\?=(.*\n.*)*' < "${BBPATH}/conf/bblayers.conf")
layers=()
for line in $bblayers; do
    if [ -z "$line" ]; then
        continue
    fi
    if [ -d "$line" ]; then
        layers+=($line)    
    fi
done
recipes=()
for layer in "${layers[@]}"; do
    # Use find to search for the .bb file with wildcards
    bb_file=$(find "${layer}/" -type f -name "${recipe}*.bb" 2>/dev/null)

    if [ -n "$bb_file" ]; then
        recipes+=(\"$bb_file\")
    fi
done
selected=$(gum choose "${recipes[@]}")
basename_recipe=$(basename "${selected%_*}")
diremeta=$(dirname "${selected#*/meta}" )
# echo "$basename_recipe"
# echo "${diremeta}"
echo -e "\e[32m Select the layer to append the recipe\e[0m]"
target_layer=$(gum choose "${layers[@]}")
append_recipe="${target_layer}"/"${diremeta}"/"${basename_recipe}"_%.bbappend
mkdir -p "${target_layer}"/"${diremeta}"
touch "$append_recipe"
echo 'FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"' >> "$append_recipe"

echo "Created ${append_recipe}"